name: 24/7 Minecraft AFK Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    steps:

    - name: "📥 Tải code từ repo Private"
      run: |
        git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/TÊN_BẠN/MINECRAFT.git bot

    - name: "⚙️ Cài Node.js 18"
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: "📦 Cài thư viện"
      working-directory: bot
      run: npm install

    - name: "🤖 Chạy bot"
      working-directory: bot
      env:
        ACC1_USERNAME: ${{ secrets.ACC1_USERNAME }}
        ACC1_LOGIN_CMD: ${{ secrets.ACC1_LOGIN_CMD }}
        ACC2_USERNAME: ${{ secrets.ACC2_USERNAME }}
        ACC2_LOGIN_CMD: ${{ secrets.ACC2_LOGIN_CMD }}
      run: npm start
